# Generated by Django 4.1.2 on 2022-10-30 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_product_board'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footerlogo', models.CharField(max_length=300)),
                ('footertext', models.CharField(max_length=100)),
                ('footerTel1', models.CharField(max_length=20)),
                ('footerTel2', models.CharField(max_length=20)),
                ('mail', models.CharField(max_length=50)),
                ('instagram', models.CharField(max_length=100)),
                ('telegram', models.CharField(max_length=100)),
                ('whatsApp', models.CharField(max_length=100)),
            ],
        ),
    ]
