# Generated by Django 4.1.2 on 2022-10-30 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_footer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footer',
            old_name='footertext',
            new_name='footerText',
        ),
    ]
