# Generated by Django 4.1.2 on 2022-10-30 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_footer_created_footer_updated_alter_footer_mail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headerLogo', models.CharField(max_length=300)),
                ('headerTel', models.CharField(max_length=20)),
                ('telegram', models.CharField(max_length=100)),
                ('whatsApp', models.CharField(max_length=100)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
