# Generated by Django 4.1.2 on 2022-10-31 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_about_advantages_help_news_publicoffer_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='text',
            field=models.CharField(max_length=2000),
        ),
    ]
